export default {
  FETCHED_ALL_NEWS: 'FETCHED_ALL_NEWS',
  FETCHED_ALL_CLIENTS: 'FETCHED_ALL_CLIENTS',
  FETCHED_ALL_PAGE_INFO: 'FETCHED_ALL_PAGE_INFO',
  UPDATE_PAGE_INFO: 'UPDATE_PAGE_INFO',

  UPLOAD_IMAGE: 'UPLOAD_IMAGE',
  UPLOAD_FILE: 'UPLOAD_FILE',
  UNLOAD_FILE: 'UNLOAD_FILE',
  
  CREATE_NEWS_ARTICLE: 'CREATE_NEWS_ARTICLE',
  UPDATE_NEWS_ARTICLE: 'UPDATE_NEWS_ARTICLE',
  DELETE_NEWS_ARTICLE: 'DELETE_NEWS_ARTICLE',
  
  CREATE_CLIENT_PROFILE: 'CREATE_CLIENT_PROFILE',
  UPDATE_CLIENT_PROFILE: 'UPDATE_CLIENT_PROFILE',
  DELETE_CLIENT_PROFILE: 'DELETE_CLIENT_PROFILE',
}