export default {
  FETCHED_ALL_NEWS: 'FETCHED_ALL_NEWS',
  FETCHED_ALL_CLIENTS: 'FETCHED_ALL_CLIENTS',
  FETCHED_SINGLE_ARTIST: 'FETCHED_SINGLE_ARTIST',
  FETCHED_ARTIST_NEWS: 'FETCHED_ARTIST_NEWS',
  UPLOAD_FILE: 'UPLOAD_FILE',
  
  CREATE_NEWS_ARTICLE: 'CREATE_NEWS_ARTICLE',
  UPDATE_NEWS_ARTICLE: 'UPDATE_NEWS_ARTICLE',
  DELETE_NEWS_ARTICLE: 'DELETE_NEWS_ARTICLE',
  
  CREATE_CLIENT_PROFILE: 'CREATE_CLIENT_PROFILE',
  UPDATE_CLIENT_PROFILE: 'UPDATE_CLIENT_PROFILE',
  DELETE_CLIENT_PROFILE: 'DELETE_CLIENT_PROFILE',
}